name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - r-askpass
  - r-assertthat
  - r-backports
  - r-base
  - r-base64enc
  - r-bh
  - r-biocmanager
  - r-bit
  - r-bit64
  - r-bitops
  - r-blob
  - r-boot
  - r-brew
  - r-brio
  - r-broom
  - r-callr
  - r-caret
  - r-cellranger
  - r-class
  - r-cli
  - r-clipr
  - r-cluster
  - r-codetools
  - r-colorspace
  - r-commonmark
  - r-covr
  - r-cpp11
  - r-crayon
  - r-crosstalk
  - r-crul
  - r-curl
  - r-data.table
  - r-dbi
  - r-dbplyr
  - r-devtools
  - r-diffobj
  - r-digest
  - r-dplyr
  - r-dt
  - r-ellipsis
  - r-essentials
  - r-evaluate
  - r-fansi
  - r-farver
  - r-fastmap
  - r-forcats
  - r-foreach
  - r-foreign
  - r-formatr
  - r-fs
  - r-generics
  - r-ggforce
  - r-ggplot2
  - r-ggraph
  - r-ggrepel
  - r-gh
  - r-gistr
  - r-git2r
  - r-glmnet
  - r-glue
  - r-gower
  - r-graphlayouts
  - r-gridextra
  - r-gtable
  - r-haven
  - r-hexbin
  - r-highr
  - r-hms
  - r-htmltools
  - r-htmlwidgets
  - r-httpcode
  - r-httpuv
  - r-httr
  - r-igraph
  - r-ini
  - r-insight
  - r-ipred
  - r-irdisplay
  - r-irkernel
  - r-isoband
  - r-iterators
  - r-jsonlite
  - r-kernsmooth
  - r-knitr
  - r-labeling
  - r-later
  - r-lattice
  - r-lava
  - r-lazyeval
  - r-lifecycle
  - r-lubridate
  - r-magrittr
  - r-maps=3.3.0
  - r-markdown
  - r-mass
  - r-matrix
  - r-memoise
  - r-mgcv
  - r-mime
  - r-modelmetrics
  - r-modelr
  - r-munsell
  - r-nlme
  - r-nnet
  - r-numderiv
  - r-openssl
  - r-pbdzmq
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-pkgload
  - r-plogr
  - r-plyr
  - r-png
  - r-polyclip
  - r-praise
  - r-prettyunits
  - r-proc
  - r-processx
  - r-prodlim=
  - r-progress
  - r-promises
  - r-pryr
  - r-ps
  - r-purrr
  - r-quantmod
  - r-r6
  - r-randomforest
  - r-rbokeh
  - r-rcmdcheck
  - r-rcolorbrewer
  - r-rcpp
  - r-rcpparmadillo
  - r-rcppeigen
  - r-rcurl
  - r-readr
  - r-readxl
  - r-recipes
  - r-recommended
  - r-rematch
  - r-rematch2
  - r-remotes
  - r-repr
  - r-reprex
  - r-reshape2
  - r-rex
  - r-rjson
  - r-rlang
  - r-rmarkdown
  - r-roxygen2
  - r-rpart
  - r-rprojroot
  - r-rsqlite
  - r-rstudioapi
  - r-rversions
  - r-rvest
  - r-scales
  - r-selectr
  - r-sessioninfo
  - r-shape
  - r-shiny
  - r-sjlabelled
  - r-sjmisc
  - r-sourcetools
  - r-spatial
  - r-squarem
  - r-stringi
  - r-stringr
  - r-survival
  - r-sys
  - r-testthat
  - r-tibble
  - r-tidygraph
  - r-tidyr
  - r-tidyselect
  - r-tidyverse
  - r-timedate
  - r-tinytex
  - r-triebeard
  - r-ttr
  - r-tweenr=1.0.1
  - r-urltools
  - r-usethis
  - r-utf8
  - r-uuid
  - r-vctrs
  - r-viridis
  - r-viridislite
  - r-waldo
  - r-whisker
  - r-withr
  - r-xfun
  - r-xml
  - r-xml2
  - r-xopen
  - r-xtable
  - r-xts
  - r-yaml
  - r-zeallot
  - r-zoo