#!/bin/bash

set -ex

R -e 'BiocManager::install("KEGGREST", update = TRUE, ask = FALSE)'
R -e 'BiocManager::install("KEGGgraph", update = TRUE, ask = FALSE)'
R -e 'BiocManager::install("pathview", update = TRUE, ask = FALSE)'
R -e 'BiocManager::install("KEGG.db", update = TRUE, ask = FALSE)'

R -e 'devtools::install(".", upgrade = "never")'